### ISSUE TITLE
Missing exported ts types

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/cockpit-api#1]
src/modules/index.ts:14:14 - error TS4023: Exported variable 'modules' has or is using name 'ImageSizeMode' from external module "/Users/pozylon/Repositories/lorem/engine/node_modules/@unchainedshop/cockpit-api/dist/api" but cannot be named.

and

src/modules/index.ts:14:14 - error TS4023: Exported variable 'modules' has or is using name 'MimeType' from external module "/Users/pozylon/Repositories/lorem/engine/node_modules/@unchainedshop/cockpit-api/dist/api" but cannot be named.

**Comment by Mikearaya** [comment]
fixed on 1.0.21
